apiVersion: apps/v1
kind: Deployment
metadata:
  name: shack-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shack
  template:
    metadata:
      labels:
        app: shack
    spec:
      containers:
        - name: shack-c
          image: praveen1351/shack:a380f2d22c13444184058556a8b9d3915a5973f4
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials
