apiVersion: apps/v1
kind: Deployment
metadata:
  name: shack-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shack
  template:
    metadata:
      labels:
        app: shack
    spec:
      containers:
        - name: shack-c
          image: praveen1351/shack:075d8036a7229d0c57cd78fe6f86ac4d3cf7c3c4
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials
