apiVersion: apps/v1
kind: Deployment
metadata:
  name: shack-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shack
  template:
    metadata:
      labels:
        app: shack
    spec:
      containers:
        - name: shack-c
          image: praveen1351/shack:76aede0dd7d5d4bac794b4a846d3349605530686
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials
