apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
type: Opaque
stringData:
  DB_HOST: database-1.cj6q60yeqbje.us-west-2.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: mydb
  DB_USER: admin
  DB_PASSWORD: Praveen123
