apiVersion: v1
kind: Service
metadata:
  name: shack-dev
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: shack
  ports:
    - port: 80
      targetPort: 5000   # ← change to whatever port your container actually listens on
