apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: shack-instrumentation
  namespace: dev
spec:
  exporter:
    endpoint: http://adot-collector-collector.monitoring.svc.cluster.local:4317
  nodejs: {}
